version: "3.8"
services:
  postgres_dev:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: drivebox_dev
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  drivebox_service:
    image: drivebox:0.0.1
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - postgres_dev
    build:
      context: .
      dockerfile: Dockerfile
